# Capítulo 2 Handbook

En este capitulo como en el 3 se revisan tecnicas para lectura, almacenamiento y manipulación efectiva de la memoria en python. Por ejemplo, las imagenes pueden verse como un arreglo bidimencional de numeros que representan pixeles y luminocidad, mientras que los clips de sonido se puede ver como arreglos unidimensionales de intenisdad contra tiempo, etc. Sin importar el tipo de dato, el primer paso para analisarlo es llevarlo a un arreglo de numeros.


NumPy y Pandas package son herramientas especializadas de Python para el manejo de arreglos numericos. En este capítulo se vera el manejo de los NumPy (Numerical Python), este paquete ofrece una interface eficiente para el almacenamiento y operación de buffers densos de datos (data buffer is a region of a physical memory storage used to temporarily store data while it is being moved from one place to another)

In [2]:
import numpy
numpy.__version__

'1.16.4'

In [3]:
import numpy as np

Como se habia mencionad Python te permite explorar rapidamente los contenidos del paquete

In [4]:
np?

Type:        module
String form: <module 'numpy' from '/Users/stefany/miniconda3/lib/python3.7/site-packages/numpy/__init__.py'>
File:        ~/miniconda3/lib/python3.7/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
 

## Understanding Data Types in Python

Python tiene la propiedad de tener una escritura dinámica, mientras que en C o Java todas las variables tienen que haber sido declaradas con anterioridad Python infiere el tipo de variable que se esta maniulando

In [5]:
# Python code
result = 0
for i in range(100):
    result += i

 For C code

Otro ejemplo de como Python infiere el tipo de variable es el siguiente

In [6]:
# Python code
x = 4
x = "four"

Cambiar de esta forma el tipo de variable para python no es un problema, sin embargo en C, dependiendo del compilador, podiria llevar a un error con consecuencias inesperadas

## A Python integer is more than just an integer

La implementación estandar de Python esta escrita en C, que contiene no solo el valor, sino tambien, otro tipo de información 

In [7]:
int?

Init signature: int(self, /, *args, **kwargs)
Docstring:     
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4
Type:           type
Subclasses:     bool, IntEnum, IntFlag, _NamedIntConstant


A diferencia de C donde un entero solo es un lugar en la memoria donde el valor del mismo esta representado por la cantidad de bytes, en Python es un apuntador a la memoria donde esta contenida toda la información.

## A Python List is more than just a list

Aqui se vera que es lo que ocurre cuando se tiene una estructura Python que contiene varios objetos Python

In [8]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(L[0])

int

Can be a list of diferent things like strings

In [10]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
type(L2[0])

str

or even heterogenius

In [12]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

El problema será que al momento de almacenar una lista con el mismo tipo de variables la información será redundante lo que ocaciona almacenamiento desperciciado

## Fixed-Type Arrays in Python

Construir un array module puede usarse para crear un arreglo de datos uniforme denso, array provee un alacenamiento eficiente de datos en base a arreglos

In [13]:
import array
L= list(range(10))
A= array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Aqui el 'i' es un tipo de codigo que indica que el contenido son enteros

Un comando más util es ndarray que ofrece operaciones entre los datos de forma eficiente 



In [14]:
import numpy as np

## Creating arrays from Python list

Usando np.array se crean arreglos de una lista de Python

In [15]:
#integer array
np.array([1,4, 2, 5, 3])

array([1, 4, 2, 5, 3])

A diferencia de las listas de Python numpy solo puede realizarce con objetos del mismo tipo, en el siguiente ejemplo los enteros se convierten a float para que coincidan

In [16]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Si se quiere dar un tipo de variabe especifico se usa dtype

In [17]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finalmente a diferencia de las listas de Python numpy puede hacer arreglos multidimensionales

In [18]:
# nested list result in multi-dimensional arrays

np.array([range(i,i+3) for i in [2,4,6]])


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays form Scratch

Para arreglos grandes a veceses mas util crear arreglos desde cero usando rutinas para convertir en NumPy

In [19]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
# Creating a floating point array filled with ones 

np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
# Create a 3x5 array filled with 3.14

np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [22]:
#Create an array filled with a linear sequence 
#Starting at 0, ending at 20, stepping by 2
#(This is similar to the built-in range() function)

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#Creating an array of five values evenly spaced between 0 and 1 

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [24]:
# Create a 3x3 array of uniformly distributed
#random values between 0 and 1

np.random.random((3,3))

array([[0.00453572, 0.43990438, 0.65334404],
       [0.13021703, 0.38597524, 0.43607185],
       [0.00895445, 0.28312931, 0.24365936]])

In [25]:
# Create a 3x3 array of normally distributed random values 
# with mean 0 and standard deviation 1

np.random.normal(0,1,(3,3))

array([[ 0.5963529 , -2.3013756 ,  1.83917857],
       [ 0.14908781,  0.38239566,  0.32187966],
       [ 1.58911053,  1.08976692,  1.00817848]])

In [26]:
# Create a 3x3 array of random integers in the interval [0,10)

np.random.randint(0,10,(3,3))

array([[6, 5, 5],
       [2, 6, 9],
       [7, 3, 7]])

In [27]:
#Create a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# Create an uninitialized array of three integers 
# The values will be whatever happens to already exist at the memor 

np.empty(3)

array([1., 1., 1.])

## NumPy Standard Data Types

Ya que los arreglos de numpy solo contienen valores del mismo tipo, por lo que se puede especificar que tipo de variable es ya sea por medio de strings o con su objeto numpy asociado

In [29]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [30]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

## 2.2 The basics of numpy arrays

### Numpy array attibutes

Se muestra como arreglos de una, dos y tres dimensiones pueden establecerce usando un generador de numeros aleatorios que se le dara la semilla on un valor establecido para asegurar que el mismo arreglo random se genere cada ves que el código corre

In [31]:
import numpy as np
np.random.seed(0)                     #semilla para reproducibilidad

x1=np.random.randint(10,size=6)       # one dimensional array
x2=np.random.randint(10,size=(3,4))   # two dimensional array
x3= np.random.randint(10, size=(3,4,5)) #Three dimensional array

Cada arreglo tiene los atributos de ndim, shape(el tamaño de a cada dimension) y size(el tamaño total del arreglo)

In [32]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


Así como el dtype, itemsize (da la lista del tamaño en bytes de cada elemento) y nbytes (da el tamaño total en bytes del arreglo)

In [33]:
print("dtype", x3.dtype)

dtype int64


In [34]:
print("itemsize", x3.itemsize, "bytes")
print("nbytes", x3.nbytes, "bytes")

itemsize 8 bytes
nbytes 480 bytes


## Array indexing: Accessing single elements

Así como se puede accesar a un solo elemento con los parentesis cuadrados, tambien es posible accesar a subarrays por medio de (:) caracter. 

x[start:stop:step]

Si alguno de estos no es especificado, se asumen los valores default a los valores start=0, stop= size of dimension,step=1.

### One dimension subarray

In [35]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [37]:
x[5:] #elements after index five

array([ 5,  6,  7,  8,  9, 10, 11])

In [38]:
x[4:7] #middle subarray

array([4, 5, 6])

In [39]:
x[::2] # every other element

array([ 0,  2,  4,  6,  8, 10])

In [40]:
x[1::2] # every other element, starting at index 1

array([ 1,  3,  5,  7,  9, 11])

cuando el step es negativo se invierte los defaults de start y stop

In [41]:
x[::-1] #all elements reversed

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [42]:
x[5::-2] #reversed every other from index 5

array([5, 3, 1])

## Multi-dimensional subarray

 Los arreglos multidimensionaes trabajan de la misma forma

In [43]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [44]:
x2[:2,:3] #two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [45]:
x2[:3, ::2] #three rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

se puede reverstir un subarray

In [46]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

#### Accesing array rows and columns

Para accesar auna sola fila o columna se puede combinar indexing y empty slice

In [47]:
print(x2[:,0]) # first column of x2

[3 7 1]


In [48]:
print(x2[0,:]) #first row of x2

[3 5 2 4]


en el caso de acceder a la fila, el : puede omitirse

In [49]:
print(x2[0]) #equivalent to x2[0,:]

[3 5 2 4]


### Sub arrays as no-copy views

Una cosa importante sobre los slice es que regresan views en lugar de copias de datos

In [50]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


extrayendo 2x2 subarray

In [51]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[3 5]
 [7 6]]


Ahora si se modifica este arreglo se vera que el arreglo original también cambia 

In [52]:
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [53]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

Para copiar explicitamente un arreglo se puede usar el comando copy()

In [54]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


 Ahora si modificamos esta copia el original se mantiene igual

In [55]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [56]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Reshaping of arrays

Para reshepe un arreglo se puede usar el metodo reshepe. Por ejemplo si se quiere poner los numeros del 1 al 9 en un arreglo de 3x3 

In [57]:
grid= np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Siempre y cuando el arreglo previo coincida con el tamaño del nuevo. Otra forma comun es llevar un arreglo unidimensional a uno de columna o fila de una matriz

In [58]:
x= np.array([1,2,3])

#row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

In [59]:
# row vector via newaxis
x[np.newaxis,:]

array([[1, 2, 3]])

In [60]:
#Column vector via reshape

x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [61]:
# Column vestor via newaxis

x[:,np.newaxis]

array([[1],
       [2],
       [3]])

## Array concatenation and splitting

Es posible combinar multiples arreglos en uno y separar un solo arreglo en multiples arreglos

### Concatenation of arrays

La union de arreglos en numpy es posible mediante los comandos np.concatenate, np.vstack y np.hstack

In [62]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

Tambien se pueden unir mas de dos arreglos

In [63]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


Tambien se puede usar para un arreglo bidimensional

In [64]:
grid=np.array([[1,2,3],[4,5,6]])

In [65]:
#concatenate along the second axis (zero-indexed)
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Si se trabaja con arreglos de diferentes dimensiones se puede usar np.vstack (vertical stack) y np.hstack (hotizontal stack)

In [66]:
x= np.array([1,2,3])
grid= np.array([[9, 8, 7],[6, 5, 4]])

#vertical stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [67]:
# horizontally stack the arrays

y=np.array([[99],
            [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

de la misma forma np.dstack los unira a lo largo del tercer eje 

## Splitting of arrays

Lo opuesto de concatenar es dividir, que se puede hacer mediante los comandos np.split, np.hsplit y np.vsplit

In [68]:
x= [1,2,3,99,99,3,2,1]

x1,x2,x3= np.split(x,[3,5])
print(x3)   ## tratar de entender el split

[3 2 1]


In [69]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [71]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Computation on NumPy Arrays: Universal Functions

Para poder tener operaciones mas rapidas una forma clave es usar operaciones vectorizadas, generalmente se implementan a traves de funciones universales (ufuncs, que pueden ser usadas para hacer calculos repetidos en elementos del arreglo mucho mas eficientes.  

## The slowness of loops

In [72]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output= np.empty(len(values))
    for i in range(len(values)):
        output[i]=1.0/values[i]
    return output

values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [73]:
big_array = np.random.randint(1,100, size=1000000)
%timeit compute_reciprocals(big_array)

2.36 s ± 42.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Toma algunos segundo realizar 1000000 de operaciones, aun que los celulares pueden realizar un mayor numero por segundo, en donde el cuello de botella es el type-checking y las funciones por cada ciclo de loop. Ya que python primero examina el tipo de objetos y realiza una busqueda dinamica de la funcion correcta que debe utilizar para ese tipo de funcion.  

## Introducing UFuncs

Para estos casos Numpy tiene una función para este tipo de estadisticas llamada operación vectorizada. Se puede lograr realizando unaoperación en el arreglo, que sera aplicada a cada elemento. Esta aproximación se diseño para llevar al loop a la compilación que realiza Numpy para obtener a una compilación mucho mas rapida

In [74]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


esta ejecucion de el arreglo grande que se tiene es mucho mas rapido que los loops de Python

In [75]:
%timeit (1.0/big_array)

3.31 ms ± 17.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Las operaciones vectorizadas en Numpy se implementan via ufunc, cuya fucnion principal es optimizar la ejecucion de operaciones repetidas en valores de arreglos Numpy. ufunc es tan flexible que es posible realizar operaciones entre dos arreglos

In [76]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

Tambien es posible operar sobre arreglos multidimencionales

In [77]:
x = np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

Las operaciones realizadas a traves de ufuncs son casi siempre mas eficientes que los loops de Python, sobre todo cuando los arreglos tienen un tamaño grande. Siempre que se encuentre un loop de esta forma tal ves sea mejor cambiarlo por una ufuncs.

## Exploring Numpy's uFuncs

Las funciones uFunc existen en dos formas: las unary ufuncs que operan con un solo input y las binary ufuncs que operan con dos inputs. 

### Array arithmetic

Las uFunc son muy naturales ya que usan las operaciones nativas de Python, la suma, multiplicación, resta y divición pueden ser usadas

In [79]:
x=np.arange(4)
print("x    =", x)
print("x + 5 =", x+5)
print("x - 5 =", x-5)
print("x * 5 =", x*5)
print("x / 2 =", x/2)
print("x // 2 =", x//2 ) ##floor division

x    = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 5 = [ 0  5 10 15]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [80]:
print("-x =", -x)
print("x ** 2 =", x**2)
print("x % 2 =", x % 2)

-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


También se puede representar como 

In [81]:
np.add(x,2)

array([2, 3, 4, 5])

### Absolute value

In [82]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

Su correspondiente Numpy function es

In [83]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [84]:
np.abs(x)

array([2, 1, 0, 1, 2])

Esta función tambien admite valores complejos, donde regresa el valor de la magnitud

In [85]:
x =np.array([3-4j, 4-3j, 2+0j, 0+1j])
np.abs(x)

array([5., 5., 2., 1.])

### Trigonometric functions 

In [87]:
theta = np.linspace(0, np.pi, 3) # Definiendo un arreglo de angulos

Ahora se pueden calcular algunas funciones trigonometricas para estos angulos

In [88]:
print("theta = ", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Ya que se calculan con la precicion de la maquina algunos valores que deverian ser cero no simpere dan cero.

In [89]:
print("arcsin(theta) =", np.sin(theta))
print("arccos(theta) =", np.cos(theta))
print("arctan(theta) =", np.tan(theta))

arcsin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
arccos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
arctan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


### Specialized ufuncs

Para funciones mas especializadas se tiene el modulo scipy.spacial

In [92]:
from scipy import special
#Gamma function (generalized factorials) and related functios

x=[1, 5, 10]
print("gamma(x) =", special.gamma(x))
print("ln|gamma(x)|", special.gammaln(x))
print("beta(x,2) =", special.beta(x, 2))

gamma(x) = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| [ 0.          3.17805383 12.80182748]
beta(x,2) = [0.5        0.03333333 0.00909091]


In [93]:
# Error function (integral of Gaussian)
#its complement, and its inverse

x= np.array([0, 0.3, 0.7, 1.0])
print("erf(x) =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x) = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


### Advanced uFunc Features

#### Specifying output

In [94]:
#Puedes especificar el lugar en el cual se guardara tu arreglo de salida
x = np.arange(5)
y= np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


Esto también se puede guardar el calculo de algunos elementos del arreglo

In [95]:
y = np.zeros(10)
np.power(2,x, out= y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


Si en lugar de esto se hubiera generado  y[::2]=2**x el resultado seria el almacenamiento temporal de 2**x seguido por la operacion de copiado a y, lo que en un calculo grande seria una perdida significativa de memoria

### Aggregates

Una de las funciones binary es la de reduce, que reduce un arreglo con una operación particular 

In [98]:
x= np. arange(1,6)
np.add.reduce(x) # Regresa la suma de todos los elementos del areglo

15

In [99]:
np.multiply.reduce(x)

120

Si se quiere almcenar todos los resultados intermedios del calculo se puede usar la funcion accumulate

In [101]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [103]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

### Outer products

Esta funcion te permite realizar una tabla de multipliación

In [104]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Aggregations: Min, Max, and Everything in Between